build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.13
  amd64: ghcr.io/home-assistant/amd64-base:3.13
  armhf: ghcr.io/home-assistant/armhf-base:3.13
  armv7: ghcr.io/home-assistant/armv7-base:3.13
codenotary:
  signer: mick@mickmake.com
  base_image: mick@mickmake.com
args:
  GOSUNGROW_VERSION: 2.2.1
